#!/usr/bin/env sh

alias v="nvim"
alias vd="nvim ."

alias ..="cd .."
alias ls="ls --color"
alias l="ls --color -lhv --group-directories-first"
alias ll="ls --color -lhva --group-directories-first"
alias grep="grep --color=auto -i"

alias lg="lazygit"
alias gl="ydiff -l"
command -v bat >/dev/null && alias cat="bat --plain --plain"

alias wifi="nmcli dev wifi list"

# Chat.
if command -v nvidia-smi >/dev/null; then
    alias ai="ollama run llama3.1"
else
    alias ai="ollama run llama3.2"
fi

# Python.
alias pa='source .venv/bin/activate'
alias pd='deactivate'
alias py='python'
alias pt='pytest --no-header'

# Zig.
alias zb="zig build"
alias zr="zig build run"
alias zt="zig build test --summary all"
alias zbb="zig build benchmark --summary all"

# Go.
alias gb="go build"
alias gr="go run"
alias gt="go test ./..."
alias gi="go install ./..."
alias gc="go clean -i"

# Docker.
alias ds="docker ps -aq | xargs -r docker stop"
alias dri="docker ps -aq | xargs -r docker rm"
alias drv="docker volume prune -af"
alias drs="docker system prune -af"
