#!/usr/bin/env bash
if [[ ! $- == *i* ]]; then
    return
fi

source "$HOME/.environment"
source "$HOME/.aliases"

# History
shopt -s histappend

# FZF
eval "$(fzf --bash)"

# Bindings
bind "\C-p":history-search-backward
bind "\C-n":history-search-forward
bind -x '"\C-g":"clear"'
bind '"\C-i":menu-complete'
bind '"\e[Z":menu-complete-backward'
bind "set show-all-if-ambiguous on"
bind "set menu-complete-display-prefix on"
