#!/usr/bin/env sh

export PS1="\w $ "
export PROMPT="%~ $ "
export EDITOR="nvim"
export VISUAL="nvim"
export TERM="tmux-256color"
export PATH="$HOME/.local/bin:$PATH"

# History
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth
export SAVEHIST=10000

# Mason
export PATH="$PATH:$HOME/.local/share/nvim/mason/bin"

# Zig version control
export ZVM_INSTALL="$HOME/.zvm/self"
export PATH="$PATH:$HOME/.zvm/bin"
export PATH="$PATH:$ZVM_INSTALL/"

# Homebrew
if [ -d /home/linuxbrew ]; then
    export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
    export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
    export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
    export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}"
    [ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}"
    export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}"
    [ -z "${XDG_DATA_DIRS-}" ] || export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:${XDG_DATA_DIRS-}"
fi

# FZF
export FZF_COMPLETION_OPTS="--preview-window=right:70%:border-none --preview 'bat --style=numbers --color=always {}'"
export FZF_CTRL_T_OPTS="--preview-window=right:70%:border-none --preview 'bat --style=numbers --color=always {}'"
export FZF_DEFAULT_OPTS="--reverse --border=none --no-separator --no-scrollbar --info=hidden"
