#!/usr/bin/env sh

if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		source "$HOME/.bashrc"
	fi
fi

# Run window manager
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	startx >/dev/null 2>&1
fi
