#!/usr/bin/env bash

if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		source "$HOME/.bashrc"
	fi
fi

# Add homebrew to path
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}"

# Run window manager
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	startx >/dev/null 2>&1
fi
