#!/usr/bin/env sh

# Load profile
[ -f "$HOME/.profile" ] && source "$HOME/.profile"

# Load Xresources
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

# Set keyboard layout
setxkbmap -layout us,fi -option grp:switch -option ctrl:nocaps

# Increase key repeat
xset r rate 250 125

# Remove beeping
xset b off

# Hide cursor after 5s
unclutter -idle 5 &

# Screen locker
xss-lock --transfer-sleep-lock -- '3lock -c 282828 -u' --nofork &

# Notifications
dunst &

# Start window manager
i3
