return {
    -- Copilot
    -- {
    --     "zbirenbaum/copilot.lua",
    --     event = "InsertEnter",
    --     config = function()
    --         local copilot = require("copilot")
    --         local suggestion = require("copilot.suggestion")
    --         copilot.setup {
    --             suggestion = {
    --                 enabled = true,
    --                 auto_trigger = false,
    --                 hide_during_completion = false,
    --                 debounce = 75,
    --                 keymap = {
    --                     accept = false,
    --                     next = "<M-]>",
    --                     prev = "<M-[>",
    --                 },
    --             },
    --             filetypes = {},
    --         }
    --         vim.keymap.set("i", "<c-space>", function()
    --             if not suggestion.is_visible() then
    --                 suggestion.next()
    --             else
    --                 suggestion.accept()
    --             end
    --         end, { desc = "Accept copilot suggestion" })
    --         vim.keymap.set("n", "<leader>tp", suggestion.toggle_auto_trigger, { desc = "Toggle copilot" })
    --     end,
    -- },
}
